version: "3.9"
services:
  postgres:
    container_name: authServer
    image: postgres:latest
    environment:
      POSTGRES_DB: "petproject"
      POSTGRES_USER: "gbcmax"
      POSTGRES_PASSWORD: "Qazxsw23"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: